// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Recommends events to users based on their past purchase history and preferences.
 *
 * - recommendEvents - A function that handles the event recommendation process.
 * - RecommendEventsInput - The input type for the recommendEvents function.
 * - RecommendEventsOutput - The return type for the recommendEvents function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const RecommendEventsInputSchema = z.object({
    purchaseHistory: z
        .string()
        .describe(
            'Uma string contendo o histórico de compras do usuário. Inclua nomes de eventos, datas e categorias de eventos para os quais o usuário comprou ingressos no passado.'
        ),
    preferences: z
        .string()
        .describe(
            'Uma string contendo as preferências do usuário, como categorias de eventos preferidas, locais e faixas de preço.'
        ),
});
export type RecommendEventsInput = z.infer<typeof RecommendEventsInputSchema>;

const RecommendEventsOutputSchema = z.object({
    recommendedEvents: z
        .string()
        .describe(
            'Uma lista de eventos recomendados, incluindo nomes de eventos, datas, locais e breves descrições.'
        ),
});
export type RecommendEventsOutput = z.infer<typeof RecommendEventsOutputSchema>;

export async function recommendEvents(input: RecommendEventsInput): Promise<RecommendEventsOutput> {
    return recommendEventsFlow(input);
}

const prompt = ai.definePrompt({
    name: 'recommendEventsPrompt',
    input: {schema: RecommendEventsInputSchema},
    output: {schema: RecommendEventsOutputSchema},
    prompt: `Você é um sistema de recomendação de eventos de IA. Você receberá o histórico de compras e as preferências do usuário como entrada e retornará uma lista de eventos recomendados.

Histórico de Compras: {{{purchaseHistory}}}
Preferências: {{{preferences}}}

Com base nessas informações, recomende eventos que o usuário provavelmente gostará. Inclua nomes de eventos, datas, locais e breves descrições.`,
});

const recommendEventsFlow = ai.defineFlow(
    {
        name: 'recommendEventsFlow',
        inputSchema: RecommendEventsInputSchema,
        outputSchema: RecommendEventsOutputSchema,
    },
    async input => {
        const {output} = await prompt(input);
        return output!;
    }
);
